- name: setup the mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing the MongoDb
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Start and the enable the mongodb service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: editing the config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart the mongodb service
  ansible.builtin.service:
    name: mongod
    state: restarted