- name: Installing the maven
  ansible.builtin.package:
    name: maven
    state: present

- name: Adding the user
  ansible.builtin.import_role:
    name: common
    tasks_from: useradd

- name: Installing the packages from files
  ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Installing the mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: checking the citeis in the mysql exsit or not
  ansible.builtin.shell: mysql -h mysql.jagadish.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: output

- name: Loading the schema
  ansible.builtin.shell: mysql -h mysql.jagadish.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
  when: output.stdout != "1"

- name: restart the shipping service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemctl