- name: Installing the yum repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Installing the yum repos for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing the rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: enable and start the rabbitmq service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create rabbitmq user
  ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

- name: setting permissions for rabbitmq
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"