- name: "stopping the {{server}}"
  tags:
  - deploy
  ansible.builtin.service:
    name: nginx
    state: stopped

- name: deleting the old code
  tags:
  - deploy
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: change new code files
  tags:
  - deploy
  ansible.builtin.shell: cd /home/centos/web

- name: pull new code files
  tags:
  - deploy
  ansible.builtin.shell: git pull

- name: coping the files the files
  tags:
  - deploy
  ansible.builtin.copy:
    src: /home/centos/web/html/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: "restart the {{server}}"
  tags:
  - deploy
  ansible.builtin.service:
    name: nginx
    state: restarted