- name: "stopping the {{server}}"
  tags:
  - deploy
  ansible.builtin.service:
    name: nginx
    state: stopped

- name: deleting the old code
  tags:
  - deploy
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Downloading new code files
  tags:
  - deploy
  ansible.builtin.git:
    repo: https://github.com/Jagadish2536/web.git
    dest: /home/centos/web
    update: yes
    version: main

- name: coping the files the files
  tags:
  - deploy
  ansible.builtin.copy:
    src: /home/centos/web/html/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: "restart the {{server}}"
  tags:
  - deploy
  ansible.builtin.service:
    name: nginx
    state: restarted