- name: "set up the {{server}} service"
  ansible.builtin.template:
    src: "{{server}}.service.j2"
    dest: "/etc/systemd/system/{{server}}.service"

- name: reloading the services
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable the service {{server}}"
  ansible.builtin.service:
    name: "{{server}}"
    state: started
    enabled: yes